### ISSUE TITLE
csfd.movie(1079) throws TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by AlesKubr1** [bartholomej/node-csfd-api#21]
Calling `csfd.movie(1079)` throws

```
TypeError: Cannot read properties of undefined (reading 'split')
    at getPremieres (...\node_modules\node-csfd-api\helpers\movie.helper.js:230:91)
    at MovieScraper.buildMovie (...\node_modules\node-csfd-api\services\movie.service.js:52:56)
    at MovieScraper.movie (...\node_modules\node-csfd-api\services\movie.service.js:17:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {stack: 'TypeError: Cannot read properties of undefine…ions (node:internal/process/task_queues:96:5)', message: 'Cannot read properties of undefined (reading 'split')'}
```

**Comment by bartholomej** [comment]
Try `node-csfd-api` version 2.4.2+., it should be working now. Thanks for the report
